grammar.js
grammar_test/functions.txt
grammar_test/types.txt
package.json
src/grammar.json

Adds support for call signatures in methods/functions and function types.

Add call signature for types in methods/functions etc

---

grammar.js
grammar_test/functions.txt
grammar_test/types.txt
package.json
src/grammar.json

Flow maybe types

---

grammar.js
grammar_test/functions.txt
grammar_test/types.txt
package.json
src/grammar.json

See https://flowtype.org/docs/modules.html#import-type.

Add Flow Import type

---

grammar.js
grammar_test/declarations.txt
grammar_test/functions.txt
grammar_test/types.txt
package.json
src/grammar.json

Add ambient declarations

---

grammar.js
grammar_test/declarations.txt
grammar_test/types.txt
src/grammar.json

https://flowtype.org/docs/objects.html#exact-object-types

Add flow exact object types

---

corpus/declarations.txt
corpus/expressions.txt
corpus/functions.txt
corpus/types.txt
grammar.js
package.json
src/grammar.json

See https://github.com/tree-sitter/tree-sitter-javascript/pull/50

Update to reflect latest expression naming in tree-sitter-javascript

---

corpus/declarations.txt
grammar.js
src/grammar.json

Also adds method signatures to class bodies for use inside ambient declarations.

Make statement block non optional in method definition

---

corpus/declarations.txt
grammar.js
src/grammar.json

Includes support for classes, property definitions, method declarations, and parameters.

Add decorators to typescript

---

corpus/types.txt
grammar.js
src/grammar.json

Based off https://github.com/Microsoft/TypeScript/pull/12386/files.

allow optional pipe in front of intersection and union

---

script/parse-examples

Gives us some basic stats on percentage of code that parses in particular example repositories.

Print out some basic parse stats

---

script/known_failures.txt
src/grammar.json
src/scanner.c

Copied from tree-sitter/tree-sitter-javascript#76.

Use external for template chars

---

common/corpus/declarations.txt
common/define-grammar.js
tsx/src/grammar.json
tsx/src/node-types.json
typescript/src/grammar.json
typescript/src/node-types.json

resolve generic types in index type queries

---

queries/tags.scm

Basic tagging of type annotations.
cc @tree-sitter/semantic-code

Tag type annotations

---

common/corpus/types.txt
common/define-grammar.js

closes #98
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/103

Support extended syntax field signatures on mapped types

---

package.json

closes https://github.com/tree-sitter/tree-sitter-typescript/issues/122

Bump tree-sitter-javascript

---

package.json

This fixes a few bugs.
Checklist:

Use the latest javascript grammar

---

common/corpus/declarations.txt
common/corpus/expressions.txt
common/corpus/functions.txt
common/corpus/types.txt
package.json
tsx/src/grammar.json
tsx/src/node-types.json
typescript/src/grammar.json
typescript/src/node-types.json

Use latest tree-sitter-javascript (commit 2c5b138)

---

common/corpus/types.txt
common/define-grammar.js
tsx/src/grammar.json
tsx/src/node-types.json
typescript/src/grammar.json
typescript/src/node-types.json
yarn.lock

Add intersection/union types to `_primary_type`

---

common/corpus/declarations.txt
common/define-grammar.js
tsx/src/grammar.json
tsx/src/node-types.json
typescript/src/grammar.json
typescript/src/node-types.json

Fix export_statement

---

common/corpus/types.txt
common/define-grammar.js
tsx/src/grammar.json
typescript/src/grammar.json

Handle `from_clause` in `export type` statement

---

README.md

Checklist:
Just a small readme update.

add information about flow typed files

---

package.json
tsx/src/grammar.json
typescript/src/grammar.json

Update tree-sitter-javascript dependency

---

common/corpus/types.txt
common/define-grammar.js
tsx/src/grammar.json
typescript/src/grammar.json

fix: fix conditional type parsing association

---

common/scanner.h
test/corpus/expressions.txt

fix: allow automatic semicolons where binary operators are valid

---

common/define-grammar.js
test/corpus/declarations.txt
test/corpus/types.txt
tsx/src/grammar.json
tsx/src/node-types.json
typescript/src/grammar.json
typescript/src/node-types.json

support `assert` in imports & parenthesized decorators
