tree-sitter/tree-sitter-typescript

- grammar.js
- grammar_test/declarations.txt
- grammar_test/types.txt
- src/grammar.json
> Typescript additions

- grammar.js
- grammar_test/expressions.txt
- src/grammar.json
I noticed we were hiding the `module` keyword in `type_op` and `member_access` rules. This leverages our `reserved_identifier` rule to gain better flexibility for those reserved keywords when used in a type operator expression or member access expression.
/cc @maxbrunsfeld
> Do not hide `module` keyword

- corpus/declarations.txt
- corpus/expressions.txt
- corpus/functions.txt
- corpus/types.txt
- grammar.js
- index.js
- package.json
- src/grammar.json
- src/scanner.c
- src/tree_sitter/parser.h
This PR updates the typescript grammar to:
1. Work with the new JavaScript grammar
2. Compile against the newest version of tree-sitter
3. Distinguish between types, properties, and regular identifiers using tree-sitter's new `alias` API
We also simplified the grammar somewhat by removing some of the duplication between ambient declarations and their non-ambient counterparts.
🍐 'd with @rewinfrey
> Update to use new aliasing features

- corpus/declarations.txt
- grammar.js
- src/grammar.json
Since method definitions can appear on one line, we need to make trailing semicolons optional.
> Add optional trailing semicolons to method definitions

- corpus/declarations.txt
- grammar.js
- src/grammar.json
> Typescript fixes

- corpus/types.txt
- grammar.js
- src/grammar.json
Seems like this was lost when allowing expressions in extends clauses.
> Allow extends clauses to have multiple interfaces

- corpus/functions.txt
- corpus/types.txt
- grammar.js
- src/grammar.json
It looks like `this` is a valid parameter identifier in TypeScript but not JavaScript. This PR adds it to the `_reserved_identifier` list and adds conflicts between `this_expression`, `_expression`, `this_type`, `required_parameter`, and `optional_parameter`. 
One of the `Super` tests changed from matching an identifier as a `this_expression` to an `identifier` with this change. It seems that in that case, it should be a `this_expression` but it really depends on whether `this` shadowed by a parameter or not. We could make `this_expression` have a higher precedence than `_expression`, but then wouldn’t arguments to a function parse as `identifier` and uses parse as `this_expression`? What do you think @maxbrunsfeld?
> Allow this to be a parameter

- corpus/expressions.txt
- grammar.js
- src/grammar.json
Since method definitions had a higher precedence, we were failing to parse subscript expressions in if-statements.
> Fix bug with subscript expressions to reserved identifiers in if statements

- corpus/types.txt
- grammar.js
- src/grammar.json
Lookup types were added in [TypeScript 2.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html) to support what I think is type-level element access.
> Add support for lookup types

- corpus/types.txt
- grammar.js
- src/grammar.json
Since `-1` and `+1` are allowed as literal types, I added a `_number` term to `literal_type` so as to avoid conflicts with adding `unary_expression`. @maxbrunsfeld unfortunately this doesn’t cover the range of the signs. Any ideas?
> Negative numbers in literal types

- corpus/declarations.txt
- grammar.js
- src/grammar.json
In Flow, ambient class declaration members can be separated by commas instead of semicolons. I don't think TypeScript supports this syntax, which is kind of odd, because it allows the use of commas in *object types* (e.g. `declare interface Foo {...}`) which are very similar to classes.
Here's an [example](https://github.com/flowtype/flow-typed/blob/ecf8a05bb633d293477acf0e4b191127776c96b6/definitions/npm/double-ended-queue_v2.1.x/flow_v0.28.x-/double-ended-queue_v2.1.x.js) from the `flow-typed` project.
This PR adds support for this type of class declaration.
/cc @joshvera - I simplified `class_body` a tad by allowing decorators to appear anywhere. This is more permissive than the spec, but it shrank the parser a bit and doesn't seem to do any harm.
> Add support for flow class declarations with comma-separated members

- .gitignore
- appveyor.yml
- corpus/declarations.txt
- grammar.js
- package.json
- script/known_failures.txt
- script/parse-examples
- src/grammar.json
- src/scanner.c
Following the work in https://github.com/tree-sitter/tree-sitter-javascript/pull/72, this updates to latest tree-sitter-javascript, adds a dedicated `script/parse-examples`, wires it up to the build and fixes a few low hanging grammar issues I found.
> Add script to parse examples and miscellaneous fixes

- corpus/declarations.txt
- corpus/functions.txt
- corpus/types.txt
- grammar.js
- src/grammar.json
I'm evaluating Atom's TypeScript syntax highlighting, which uses this parser, and found some cases where identifiers were being highlighted as types inconsistently. We already have a `type_identifier` rule that we apply via aliases in certain cases, but this PR applies it in more cases.
> Differentiate type identifiers from other identifiers more consistently

- .gitignore
- grammar.js
- src/grammar.json
This pull request seeks to address two issues currently when trying to generate the TypeScript grammar using the latest JavaScript grammar:
```
Error: Unresolved conflict for symbol sequence:
'new'  function  arguments  •  '*'  …
```
```
Error: Unresolved conflict for symbol sequence:
'new'  'async'  '('  ','  •  ')'  …
```
Paired on this with @tclem and @maxbrunsfeld 
Depends on https://github.com/tree-sitter/tree-sitter-javascript/pull/95
Refs https://github.com/tree-sitter/tree-sitter-javascript/pull/89
> Fix upstream issues with JS grammar

- corpus/types.txt
- grammar.js
- src/grammar.json
Adds support for `import {type Foo} from 'bar'` Flow syntax
Fixes #65
> Support more flow import type syntax

- package.json
- properties/highlights.css
- src/highlights.json
This PR adds a *property sheet* to the repo that applies a `scope` property to nodes for the purposes of syntax highlighting. The current `scope` values are based on a new schema: https://github.com/tree-sitter/highlight-schema. These values are meant to be easily mappable to various theming systems, including Atom.
> Add a property sheet for syntax highlighting

- common/define-grammar.js
- typescript/corpus/types.txt
- typescript/src/grammar.json
TypeScript 2.1 added support for [mapped types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html).
Resolves https://github.com/tree-sitter/tree-sitter-typescript/issues/70.
> Add mapped type support

- typescript/index.js
Hey @maxbrunsfeld!  Looks like native require paths for the TypeScript grammar have been broken since 0.15.2 due to commit ab9ab6c.  This PR fixes the relative path to the native module.
> Fix native require paths in TypeScript grammar

- common/corpus/functions.txt
- common/define-grammar.js
- package.json
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This should work with the latest [tree-sitter-javascript as of today](https://github.com/tree-sitter/tree-sitter-javascript/pull/138). The tests pass. I added just one test that combines types and optional chaining.
to: @maxbrunsfeld
> Update for latest tree-sitter-javascript (take 2)

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This adds support for "assertion functions". Instead of the return type of the function, we have `asserts id` or `asserts id is typ`. See 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions
> Add support for assertion functions

- common/corpus/declarations.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
In a variable or lexical declaration, placing an exclamation mark before the type annotation allows and in fact requires, omitting the initializer. This feature makes sense for mutable variables declared with `var` or `let`. It does not make sense for `const` but we support const anyway out of convenience.
Valid:
```
let x!: t;
var x!: t;
```
Invalid in typescript but tolerated by this implementation:
```
const x!: t;
```
Invalid in both typescript and in this implementation:
```
let x!: t = y;
```
> Add support for definite assignment assertions

- common/define-grammar.js
- tsx/corpus/expressions.txt
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
`jsx_self_closing_element` now works just like `jsx_opening_element`, allowing an element name followed by type arguments.
> Support type arguments in self-closing jsx elements.

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This adds support for the special syntax for read-only arrays. It's not much code and the tests pass... but please note the following:
* I removed the right-precedence annotation because I don't see how or when it would apply. I may be missing something.
* I specified a precedence of `PREC.ARRAY_TYPE+1` so as to make `readonly` less sticky. Not sure if declaring a name for the new precedence value would be better.
> Add support for readonly array types ('readonly x[]')

- common/corpus/types.txt
- common/scanner.h
This fixes https://github.com/tree-sitter/tree-sitter-typescript/issues/93 as suggested by @maxbrunsfeld.
> Disable automatic semicolon insertion before colon

- common/corpus/declarations.txt
- package.json
- tsx/src/grammar.json
- tsx/src/node-types.json
- tsx/src/tree_sitter/parser.h
- typescript/src/grammar.json
- typescript/src/node-types.json
- typescript/src/tree_sitter/parser.h
Follow-up from https://github.com/tree-sitter/tree-sitter-javascript/commit/3d9fe9786ee74fa5067577f138e1a7129f80fb41
- Bump `tree-sitter-javascript` in `package.json` to https://github.com/tree-sitter/tree-sitter-javascript/commit/3d9fe9786ee74fa5067577f138e1a7129f80fb41
- Bump `tree-sitter-cli` (par for the course, as it was done in the other PRs)
- Regenerate the parser
> Regenerate parser for "else_clause"

- common/corpus/expressions.txt
- common/define-grammar.js
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/107
Code changes are ready. The PR is currently marked as "Draft" because it requires changes in tree-sitter-javascript (https://github.com/tree-sitter/tree-sitter-javascript/pull/146).
> Support assignment for non_null_assertion in the LHS

- common/corpus/types.txt
- common/define-grammar.js
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/99
I'm not regenerating the parser here because #110 hasn't landed yet
> Refine keyof/typeof and its tests

- common/corpus/types.txt
- common/define-grammar.js
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/96
This takes "patch-a-hole" approach from the use-case linked in the issue, but the solution might not be complete. As of writing this, I am not sure if any arbitrary type is allowed on the assertion expression's left side; I tried to learn from the following resources, but the my findings were inconclusive.
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions
- https://github.com/microsoft/TypeScript/blob/d163ab67c82460b7177e7e93a3e80659a9ef75fb/src/compiler/parser.ts#L246
- https://github.com/microsoft/TypeScript/blob/d163ab67c82460b7177e7e93a3e80659a9ef75fb/src/compiler/types.ts#L2410
The trail above leads to `TypeNode`, which I couldn't find the definition of. It …
> Allow "this" in type assertions

- common/corpus/types.txt
- common/define-grammar.js
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/82
enables https://github.com/tree-sitter/tree-sitter-typescript/issues/101
Given the context in https://github.com/tree-sitter/tree-sitter-typescript/pull/112#discussion_r530132836, I've taken what was described as the "second approach" of not having `type_predicate` be considered as a type (as it was previously). I think this turned out to be preferable to the previous PR since type predicate assertions are quite special and restricted in their usage.
For the conditional types and functions interplay, I'm using the following code as reference for the precedence rules.
https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgPAFQDRQBooJoD4oF4oAUwAXFAgJR46pQQAewEAdgCYDOUGUA-GlKRgBQg0JFgw8sOEwCuAWwBGEAE4pZilWvlLlWYaOgBxRCnScc+ …
> Conditional types take two

- common/corpus/expressions.txt
- common/define-grammar.js
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/102
> Fix precedence order for as_expressions

- common/corpus/types.txt
- common/define-grammar.js
Workaround for E5084
```Tuple members must all have names or all not have names. (5084)```
Incited by comment https://github.com/tree-sitter/tree-sitter-typescript/pull/118#discussion_r532865757
src/parser.c
```
#define STATE_COUNT 3133
#define LARGE_STATE_COUNT 636
```
> Tuple types enhancements - second implementation (relax E5084)

- common/corpus/declarations.txt
- common/define-grammar.js
- typescript/src/grammar.json
- typescript/src/node-types.json
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/105
> Support decorators on abstract classes

- .gitignore
- common/corpus/functions.txt
- common/corpus/types.txt
- common/define-grammar.js
- common/scanner.h
- script/known_failures.txt
- script/parse-examples
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/95
> Fix ambiguity between function signature and function declaration

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
note: This is on top of https://github.com/tree-sitter/tree-sitter-typescript/pull/123, so that it can be built properly
---
Test cases have been adapted from [Type inference in conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#type-inference-in-conditional-types), except for the following scenario
`type ReturnType<T extends (...args: any[]) => infer R> = R; // Error, not supported`
Since it's not supported by TypeScript, it's not handled here, either.
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/101
> Support "infer" types

- .gitignore
- Cargo.toml
- bindings/rust/tsx/Cargo.toml
- bindings/rust/tsx/README.md
- bindings/rust/tsx/src/build.rs
- bindings/rust/tsx/src/lib.rs
- bindings/rust/typescript/Cargo.toml
- bindings/rust/typescript/README.md
- bindings/rust/typescript/src/build.rs
- bindings/rust/typescript/src/lib.rs
This PR adds a `Rust` package for `tree-sitter-tsx` and `tree-sitter-typescript` grammars. 
This makes it easier to use the Rust tree-sitter bindings with a statically known set of languages, since you can just list them as normal `Rust` dependencies, instead of having to embed the grammar and set up a `build.rs` file yourself.
Thanks in advance for your review! :)
> Add Rust package

- .github/workflows/build.yml
This was previously configured to use a branch pattern that
would only match illegal branch names.
> Use GHA on all pull requests

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- typescript/src/grammar.json
The typeof keyword has a slightly unexpected precedence in a typed
context. That is,
type Foo = typeof my_array[number]
should be interpreted as
type Foo = ((typeof my_array)[number])
This commit fixes this grammar to have the above precedence.
This can be confirmed by attempting to type-check the following code:
const my_array = ["a", "b", "c"];
type MA = (typeof my_array)[number];  // MA = "string"
type MB = typeof (my_array[number]);  // throws errors
Note that this leaves a similar issue (#149) with keyof lookups unresolved.
Fixes #141.
> Fix lookup type precedence

- common/corpus/types.txt
- common/scanner.h
"object_type" nodes admit automatic semicolons, whereas "object_pattern"
nodes do not. The current grammar will greedily attempt to consume an
object_type node, and insert an automatic semicolon within this type:
({a}: {a: number}) => number
Since object types can never themselves be typed, I use two-token
lookahead when deciding to insert an automatic semicolon before the
closing braces of a braced sequence of tokens; if a type annotation
follows the closing brace, we will not allow an automatic semicolon.
Fixes https://github.com/tree-sitter/tree-sitter-typescript/issues/144.
> Disable automatic semicolon insertion at end of object patterns

- common/corpus/declarations.txt
- common/define-grammar.js
- package.json
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This is the continuation of #125. It uses the latest tree-sitter-javascript which now supports extended `export` syntax for javascript.
Checklist:
STATE_COUNT in src/parser.c).
> Extend export syntax, piggybacking on javascript grammar

- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
`npm` is still a mystery to me. I never know what to invoke to update dependencies.
In `{tsx,typescript}/src/grammar.json`, I looked for `private_property_identifier` which is a recent addition to tree-sitter-javascript. It's now present, so I assume this time I did the right thing.
Originally, I had just modified `package.json` by hand, followed by `npm install`. I suppose this is deeply wrong since the generated `grammar.json` still inherited from the older tree-sitter-javascript grammar.
This time, I did this:
```
npm install github:tree-sitter/tree-sitter-javascript#ae9bc67
```
followed by
```
npm run build
npm test
```
I think code generation should be automated to avoid this kind of problems.
Checklist:
> Regenerate files, which hadn't picked up the correct version of tree-sitter-javascript

- README.md
Note that the spec is out-of-date and no longer being updated.
> Fix link to TS spec in README

- common/corpus/expressions.txt
- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- tsx/src/tree_sitter/parser.h
- typescript/src/grammar.json
- typescript/src/node-types.json
- typescript/src/tree_sitter/parser.h
:exclamation: on top of #135 for convenience's sake; there's no apparent code dependency between them. I can try to split the relevant commits for #136 (named `implement template literal types`) and #137 (named `implement "mapped type 'as' clasues"`)  upon demand.
closes #137 
closes #136
> "Template literal types" and "Mapped type 'as' clauses"

- common/corpus/declarations.txt
- common/define-grammar.js
- tsx/src/grammar.json
- typescript/src/grammar.json
Closes https://github.com/tree-sitter/tree-sitter-typescript/issues/140
Why it works is already explained in the comment. I had the idea by looking at the following line:
https://github.com/tree-sitter/tree-sitter-typescript/blob/d08f57f2689f9006c8a362454a6070d578aa8017/common/scanner.h#L118-L119
Given that method definitions are also functions and therefore their definition is similar, I thought it was fine to re-use that token instead of creating a new one.
---
**Initial** measurements of `parser.c` against d08f57f2689f9006c8a362454a6070d578aa8017
typescript:
```diff
-#define STATE_COUNT 5987
-#define LARGE_STATE_COUNT 1269
+#define STATE_COUNT 6031
+#define LARGE_STATE_COUNT 1270
```
tsx:
```diff
-#define STATE_COUNT 6292
-#define LARGE_STATE_COUNT 1270
+#define STATE_COUNT 6336 …
```
> Have special semicolon rules for method definitions

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
`type_query` is right now defined as follows:
https://github.com/tree-sitter/tree-sitter-typescript/blob/74a2748896434c13cac7697c4d182b43ec170d30/common/define-grammar.js#L660
`typeof generic_type` is not valid TypeScript syntax and does not make sense.
Using `primary_expression` causes the parsing errors described in https://github.com/tree-sitter/tree-sitter-typescript/issues/171. I found that it's possible to work around that by defining stricter variants of `call_expression`, `subscript_expression` and `member_expression` according to what I tried in the TypeScript playground. This is more restrictive than allowing all primary expressions like done right now, but it seems to work, so I'm submitting the PR here in case it's useful.
---
**Initial** measurements of `parser.c` against …
> Fix typeof according to TypeScript rules 

- common/corpus/declarations.txt
- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
closes https://github.com/tree-sitter/tree-sitter-typescript/issues/164
This is on top of #183 for my own convenience
I could not clearly distinguish `literal_type` from `predefined_type`. I added `null` and `undefined` to `literal_type` because those types are also values (is that the distinction?), while `unknown` is not.
Checklist:
> Add more predefined and literal types 

- .github/workflows/build.yml
- script/check-generated-files
This PR adds a step to the build workflow that builds the grammar and checks if the generated files change w.r.t. to the files in HEAD.
The goal is to prevent problems when the grammar is updated but the generated files are forgotten, which causes invalid tests results as these are ran using the generated files.
By running `npm run build` in the workflow and checking that the generated files in HEAD are the same as the ones produced by the CI build, we prevent inconsistencies between grammar and generated files.
I have tested this locally using `act`, but I should note that I do not have a lot of experience with workflows.
This should prevent issues like #193 in the future.
> Add a CI step that checks whether the generated files are up-to-date

- script/check-generated-files
This PR fixes two issues concerning builds and CI.
1. A bug in `script/check-generated-files` that would cause the build to fail, even though files were not actually changed. The fix was to update the index before running the diff command.
2. ~Add lock files to the repository, so that the CI build is run with exactly the same package versions as a local build. Without this, the CI build will always use the latest allowed version, which my produce different results from the local build. With the lock files in the repository, builds become predictable and problems because of accidental differences between CI and local environments are reduced. Updating packages becomes an explicit action: run `npm update` and commit the updated lock files.~
> Fix build reproducability and CI check

- common/define-grammar.js
> Document why module block is optional

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- typescript/src/grammar.json
The precedence for `type_query` needs to be higher than that of
`_type_query_subscript_expression`. Otherwise, the parser will generate
incorrect parses, and even fail to parse valid code in some cases.
The code `type X1 = typeof Y[keyof typeof Z];` should actually have
`typeof Y` grouped together. I verified this in astexplorer.net, and I
verified that TypeScript itself does parse this line. Currently, it
fails to parse using this tree-sitter grammar. Because of the incorrect
precedence, it expects an expression between the brackets instead of a
type.
I also used AST Explorer to check how TypeScript parses the other tests
that changed. In both cases, the updated parse is correct.
Checklist:
> Fix type_query precedence

- common/scanner.h
skip() was used after the qmark token has been read, which resets the start position of the token:
https://github.com/tree-sitter/tree-sitter/blob/9df064c9fe31d35dc48244a6675588aee2d61a41/lib/src/lexer.c#L184
I also moved the mark_end earlier such that the qmark token does not include trailing whitespace in its range.
One could argue that the behavior of advance(skip=true) in tree-sitter should be changed instead but I'm not sure about the implications for other external parsers. (E.g., make it so that the start_position is only moved up during advance(skip=true) if no mark_end call has occurred yet).
Fixes https://github.com/tree-sitter/tree-sitter-typescript/issues/200
As pointed out in the issue and also to my knowledge, there is currently no simple way to provide automated tests for …
> Fix empty range for ternary question mark

- common/corpus/declarations.txt
- common/corpus/expressions.txt
- common/define-grammar.js
- queries/highlights.scm
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
Support the new [satisfies operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#the-satisfies-operator) added in TypeScript 4.9
Checklist:
- Renamed `as_expression` to `cast_expression` that supports `as` and `satisfies`. Could alternatively just create a new `satisfies_expression` rule.
> Support satisfies operator

- .github/workflows/publish_crate.yml
- Cargo.toml
- package.json
This PR bumps the version to 0.20.2 to enable a new release. It also adds an action to automatically publish a new crate when a version tag is pushed.
Because the discussion regarding version schemes has not yet been resolved (partly due to my own lack of effort), I have chosen to stick for now with the current convention of staying on the tree-sitter version, and increment the patch version only.
> Release version 0.20.2

- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- typescript/src/grammar.json
Fixes https://github.com/tree-sitter/tree-sitter-typescript/issues/234
The following should parse correctly ([TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnAZlCI4HIB0A9AKoDOKU+AVqbgNwBQAxhAHakQA2K+nEA5gAokqAJSMgA)) ([Flow playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYBAntgKZhR5yZgDkAdMAKoDO5ejAVm-QNyoAxnAB2bODHKN4AcwAUpCgEpBQA)):
```ts
import type from './User.js';
```
Before:
```
(program
(import_statement
(ERROR (identifier)) (string (string_fragment)))
```
After:
```
(program
(import_statement
(import_clause (identifier)) (string (string_fragment)))
```
Checklist:
> Fix edge cases with type imports

- .gitignore
- Package.swift
- bindings/swift/TreeSitterTypeScript/typescript.h
This adds Swift bindings and Swift Package Manager (SPM) support. This should require no maintenance on your part, and should not impact the actual parsers in any way. Other similar changes were made here:
https://github.com/tree-sitter/tree-sitter-go
https://github.com/tree-sitter/tree-sitter-c
https://github.com/tree-sitter/tree-sitter-haskell
This one is a little special, because of the two parsers. At first, I thought I could use a similar approach to https://github.com/MDeiml/tree-sitter-markdown, which also has two. However, the project is structured in a way that SPM cannot quite handle (the gitignores for the sub directories in particular). So, I just combined the two parsers into one single static lib target. I suppose this adds a binary size penalty for someone that only wanted …
> SPM support

- common/corpus/declarations.txt
- common/define-grammar.js
- package.json
- tsx/corpus/expressions.txt
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This pull request brings the changes from tree-sitter/tree-sitter-javascript#227 to the Typescript grammar, and fixes what needs to be fixed in the grammar and tests here.
Checklist:
> Various fixes for JSX support

- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This will keep query compatibility with javascript
Ping @guillaumebrunerie for reference since they're related to your recent changes
Checklist:
> fix: add alias for nested_identifiers from javascript grammar

- common/corpus/declarations.txt
- common/corpus/functions.txt
- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This pull request fixes five instances of valid code not being parsed correctly (mostly due to new or somewhat advanced features):
- Support for the `unique symbol` type (see [here](https://www.typescriptlang.org/docs/handbook/symbols.html#unique-symbol)):
```typescript
const sym: unique symbol = Symbol();
```
- Correct parsing of `as const` (it is currently being parsed as if `const` were a type, but it is a keyword):
```typescript
const str = "foobar" as const;
```
- Support for `asserts` in type declarations (see also longer description at #250):
```typescript
declare const f: (x: any) => asserts x;
```
- Support for `const` type parameters (see [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters)):
```typescript
const f = <const …
```
> Various fixes for valid code not being parsed properly

- common/corpus/expressions.txt
- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
Add support for instantiation expressions (see #256 and [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions))
Instantiation expressions are expressions of the form `f<T>`, similar to a generic function call but without arguments.
In this pull request I have
- added a new `$.instantiation_expression` rule, with lower precedence than `call` so that `f<T>(x)` still gets interpreted as a call with type arguments, and not as `(f<T>)(x)`,
- added a new `$._type_query_instantiation_expression` rule in order to support the construction `typeof f<T>`,
- ~~**removed** the special parsing of `class A extends B<T>`, so that now `extends` simply expects an expression (instead of an expression and optionally type arguments), and the `B<T>` …
> Add support for instantiation expressions

- .github/workflows/publish.yml
This PR updates the publish workflow to also create a GitHub release when a version tag is pushed.
> Create GitHub releases for version tags

- queries/highlights.scm
Updates the surrounding tokens for content-tag, `<template>` (the entirety of the contents here are passed to a sub-language, glimmer in this case in the screenshots)
Before:
After: 
Info on content_tag:
- Rust Parser: https://github.com/embroider-build/content-tag/
- Spec: https://wycats.github.io/polaris-sketchwork/content-tag.html
> Update highlights.scm for content_tag

- common/corpus/expressions.txt
- common/corpus/types.txt
- common/define-grammar.js
- tsx/src/grammar.json
- tsx/src/node-types.json
- typescript/src/grammar.json
- typescript/src/node-types.json
This pull request exposes `_template_chars` as `string_fragment` in template string types. The same change was made for regular template strings in Javascript recently, which made it much easier to do syntax highlighting for them, so it makes sense to do it for template string types too.
> Expose string fragments in template string types

- common/define-grammar.js
- test/corpus/declarations.txt
- tsx/src/grammar.json
- typescript/src/grammar.json
This fixes #283, I added a test case for what was failing before, that now passes.
> fix: decorator_call_expression type arguments

- bindings/node/index.js
This unblocks using `tree-sitter-typescript` in [single-file executables](https://bun.sh/docs/bundler/executables)
This is the same as https://github.com/tree-sitter/node-tree-sitter/pull/230, except specifically for `tree-sitter-typescript` instead of `tree-sitter`.
`node-gyp-build` performs runtime checks for figuring out where the `.node` file is, but those runtime checks are difficult for static analysis to figure out where the `.node` file is. If we can rely on the prebuild to exist, we can use a template string and Bun will inline the `process.platform`, `process.arch`, and `process.versions.bun` fields within `--compile`.
Related PRs:
- https://github.com/tree-sitter/node-tree-sitter/pull/230
- https://github.com/oven-sh/bun/pull/14940
- https://github.com/oven-sh/bun/pull/14935
- …
> Support single-file executables via `bun build --compile`
